#!/bin/bash
#
# Installation instuctions:
#   sudo apt-get install ffmpeg python-scipy
#   sudo apt-get install python-matplotlib (debugging only)
#
# Comments:
#    maurits@vdschee.nl
#

CONVERT="`which ffmpeg ` -v quiet -i"
if [ $? -eq 1 ]; then
  echo "Cannot find 'ffmpeg' executable, is 'ffmpeg' installed?"
  exit -1
fi

if [ $# -eq 0 ]; then
  echo "usage: $0 audio_file.flac"
  exit 0
fi

for CURR_FILE in "$@"
do
    $CONVERT "$CURR_FILE" "/tmp/fakeflac_$$.wav"
    if [ -f "/tmp/fakeflac_$$.wav" ]; then
      echo -n "$(basename $0): $CURR_FILE: "  >&2
      python "$(dirname $BASH_SOURCE)/fakeflac.py" "/tmp/fakeflac_$$.wav"
      RESULT=$?
      rm "/tmp/fakeflac_$$.wav"
    fi
done
exit $RESULT
